# For more details, see https://docs.github.com/en/actions
name: Build and push docker image

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      ubuntu_version:
        description: 'Ubuntu version'
        required: true
        default: '22.04'
        type: choice
        options:
        - '22.04'
        - '20.04'
      platforms:
        description: 'Host platforms'
        required: true
        default: 'linux/amd64'
        type: choice
        options:
        - 'linux/amd64'
        - 'linux/arm64'
        - 'linux/amd64,linux/arm64'

# For more details, see https://github.com/docker/build-push-action
jobs:
  build-push:
    name: ${{ inputs.ubuntu_version }} / ${{ inputs.platforms }}
    runs-on: ubuntu-${{ inputs.ubuntu_version }}
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER_NAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push on 20.04
        if: ${{ inputs.ubuntu_version == '20.04' }}
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: ${{ inputs.platforms }}
          build-args: |
            UBUNTU_VERSION=${{ inputs.ubuntu_version }}
            ROS_DISTRO=galactic
          tags: |
            ${{ inputs.image_name }}:${{ inputs.image_tag }}-${{ inputs.ubuntu_version }}
            ${{ inputs.image_name }}:latest
      -
        name: Build and push on 22.04
        if: ${{ inputs.ubuntu_version == '22.04' }}
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: ${{ inputs.platforms }}
          build-args: |
            UBUNTU_VERSION=${{ inputs.ubuntu_version }}
            ROS_DISTRO=humble
          tags: |
            ${{ inputs.image_name }}:${{ inputs.image_tag }}-${{ inputs.ubuntu_version }}
            ${{ inputs.image_name }}:latest
